- name: Проверить конфигурацию sshd
  ansible.builtin.command: /usr/sbin/sshd -t
  changed_when: false
  listen: Перезапустить sshd

- name: Перечитать конфигурацию sshd
  ansible.builtin.systemd_service:
    name: ssh
    state: reloaded
  listen: Перезапустить sshd

- name: Перезапустить fail2ban
  ansible.builtin.systemd_service:
    name: fail2ban
    state: restarted

- name: Перезапустить journald
  ansible.builtin.systemd_service:
    name: systemd-journald
    state: restarted
